In [2]:
x = 5
y = 10.5

type(y)

float

In [3]:
first_name= 'Stephen'
surname = 'Carter'
full_name = first_name + ' ' + surname

full_name

'Stephen Carter'

In [16]:
# Lists
list_1 = [x, y, full_name]
type(list_1)
list_1

list_3 = list(range(10))
list_3[::-1] # reverse the entire list

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [19]:
# Dictionaries
# key:value pairs
# Tip: More readable to list pairs on separate lines
dict_1 = {'a':1,
          'b':10,
          'c':51.5}
type(dict_1)
dict_1

dict_1.keys()

dict_keys(['a', 'b', 'c'])

In [37]:
# Dataframes

import pandas as pd

# dictionary of lists
df_1 = pd.DataFrame({
    'CHILD':['Will', 'Ramanjit', 'Stephen'],
    'Borough':['Norwich','Riverview','Newham']
})

# list of dictionaries (preferred)
df_2 = pd.DataFrame([
    {'CHILD':'Will',
     'Borough':'Norwich',
     'Employer':'D2I'},
    {'CHILD':'Stephen',
     'Borough':'Newham',
     'Employer':'LIIA'},
    {'CHILD':'Ramanjit',
     'Borough':'Riverview',
     'Employer':'LIIA'}
])

condition_1 = df_2['Employer'] == 'D2I'
condition_2 = df_2['Borough'] == 'Riverview'

df_2[condition_1 | condition_2]

      CHILD    Borough Employer
0      Will    Norwich      D2I
2  Ramanjit  Riverview     LIIA

In [38]:
url = 'https://raw.githubusercontent.com/data-to-insight/ERN-sessions/refs/heads/main/data/ChildIdentifiers.csv'

child_identifiers = pd.read_csv(url)

child_identifiers

,Unnamed: 0,LAchildID,UPN,FormerUPN,UPNunknown,PersonBirthDate,ExpectedPersonBirthDate,GenderCurrent,PersonDeathDate
0,0,RND000215205141,A850728973744,NaN,NaN,2019-12-06,NaN,1,NaN
1,1,RND000824303014,A141396438491,NaN,NaN,2011-04-27,NaN,9,NaN
2,2,RND000750143123,A929946861554,NaN,NaN,2017-06-06,2019-12-06,1,NaN
3,3,RND000909164501,A612330267292,NaN,NaN,2014-10-03,NaN,0,NaN
4,4,RND000382171815,A604459366806,NaN,NaN,2019-09-25,NaN,2,NaN
...,...,...,...,...,...,...,...,...,...
327,327,RND000112711501,A465246916125,NaN,NaN,2010-07-07,NaN,2,NaN
328,328,RND000513120794,A540014111973,NaN,NaN,2018-08-14,NaN,2,NaN
329,329,RND000541643134,A549582689058,NaN,NaN,2021-12-09,NaN,51,NaN
330,330,RND000404939452,A889492349196,NaN,NaN,2013-07-23,NaN,2,NaN
331,331,RND000589802835,A877624860226,NaN,NaN,2021-10-25,NaN,9,NaN